### ISSUE TITLE
 Insert HTML line breaks before all newlines in diff comments

### ISSUE THREAD

**Issue by 11tomes** [zacharymarshal/Differ#7]
When adding comments to the diff during diff submission, I can format my comments in multiple lines. However, When they're displayed on the diff site, they appear as one line.

HTML line breaks should be inserted before all newlines in diff comments or replace them during display.

**Comment by zacharymarshal** [comment]
If you want a new line you would have to add an extra newline.
http://michelf.ca/projects/php-markdown/concepts/

However, it might be better to just change it by extending the class and doing something like: http://stackoverflow.com/questions/2092966/how-to-treat-single-newline-as-real-line-break-in-php-markdown

Try here: http://michelf.ca/projects/php-markdown/dingus/

One thing that could help syntax issues like this would be to add a preview just like github's preview.

**Comment by tbasilio** [comment]
Let's give it a try

On Fri, Jun 7, 2013 at 8:01 AM, Zachary Rankin notifications@github.comwrote:

> If you want a new line you would have to add an extra newline.
> http://michelf.ca/projects/php-markdown/concepts/
> 
> However, it might be better to just change it by extending the class and
> doing something like:
> http://stackoverflow.com/questions/2092966/how-to-treat-single-newline-as-real-line-break-in-php-markdown
> 
> Try here: http://michelf.ca/projects/php-markdown/dingus/
> 
> One thing that could help syntax issues like this would be to add a
> preview just like github's preview.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zacharyrankin/Differ/issues/7#issuecomment-19112293
> .

## 

Taylor Basilio / tbasilio@codingavenue.com
Coding Avenue / http://codingavenue.com
+1 (951) 808 - 5597
